// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    EchartsComponent: typeof import('./src/components/echartsComponent.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTree: typeof import('element-plus/es')['ElTree']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputComponents: typeof import('./src/components/inputComponents.vue')['default']
    QRcode: typeof import('./src/components/QRcode.vue')['default']
    QRcodeOption: typeof import('./src/components/QRcodeOption.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TreeSelect: typeof import('./src/components/treeSelect.vue')['default']
  }
}

export { }
